# Generated by Django 3.0.7 on 2020-07-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0002_book_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='Null', upload_to='test/')),
            ],
        ),
    ]
